In [10]:
import numpy as np
row = []
n = int(input("enter number of unknowns"))
[  row.append(float(input(" "))) for i in range(0,n) for j in range(0,n+1)]
a = np.array(row).reshape(n,n+1)
print(a)
b = 1
for j in range(0,n-1):
    for i in range(b,n):
        a[i:i+1,:]  =  a[i:i+1,:] - ((a[i:i+1,j:j+1]/a[j:j+1,j:j+1]) * (a[j:j+1,:]))
    b+=1
print(a)
x = np.ones(n)
x[n-1] = (a[-1,n]/a[n-1,n-1])
for i in range(n-2,-1,-1):
    sum = 0
    for j in range(i+1,n):
        sum += a[i,j]*x[j]
    x[i] = (a[i,n]-sum)/a[i,i]
for i in range(n):
    print("x",i,"=",x[i])

enter number of unknowns3
 25
 5
 1
 106.8
 64
 8
 1
 177.2
 144
 12
 1
 279.2
[[ 25.    5.    1.  106.8]
 [ 64.    8.    1.  177.2]
 [144.   12.    1.  279.2]]
[[ 25.      5.      1.    106.8  ]
 [  0.     -4.8    -1.56  -96.208]
 [  0.      0.      0.7     0.76 ]]
x 0 = 0.2904761904761892
x 1 = 19.690476190476197
x 2 = 1.0857142857142739
