# QUADRATIC FITTING

In [12]:
'''X = [0,1,2,3,4,5] Y = [2.1,7,7,13.6,27.2,40.9,61.1]'''


'x = [0,1,2,3,4,5] y = [2.1,7,7,13.6,27.2,40.9,61.1]'

In [1]:
import numpy as np
x =             []
y   =           []
first_row =     []
second_row =    []
third_row =     []
sum_y =         []
sum_x_y =       []
sum_x_square_y= []
x_square =      []
x_square_y =    []

n = int(input("enter total number of elements elements : "))
for i in range(0,n):
    Elements_of_x = int(input("enter elements of x: "))
    Elements_of_y = float(input("enter elements of y: "))
    x.append(Elements_of_x)
    y.append(Elements_of_y)
def power(lst,power):
    return [i**power for i in lst]

first_row.append(n)
first_row.append(np.sum(power(x,1)))
first_row.append(np.sum(power(x,2)))

second_row.append(np.sum(power(x,1)))
second_row.append(np.sum(power(x,2)))
second_row.append(np.sum(power(x,3)))
                  
third_row.append(np.sum(power(x,2)))
third_row.append(np.sum(power(x,3)))
third_row.append(np.sum(power(x,4)))

sum_y.append(np.sum(power(y,1)))
sum_x_y.append((np.sum(np.multiply(x,y))))
x_square.append(power(x,2))
x_square_y.append(np.multiply(x_square,y))
sum_x_square_y.append(np.sum(x_square_y))
                  
A = np.array([first_row , second_row , third_row])
A = np.linalg.inv(A)
print(A)
B = np.array([sum_y , sum_x_y , sum_x_square_y])
print(B)
C = np.matmul(A,B)
print(C)

enter total number of elements elements : 6
enter elements of x: 0
enter elements of y: 2.1
enter elements of x: 1
enter elements of y: 7.7
enter elements of x: 2
enter elements of y: 13.6
enter elements of x: 3
enter elements of y: 27.2
enter elements of x: 4
enter elements of y: 40.9
enter elements of x: 5
enter elements of y: 61.1
[[ 0.82142857 -0.58928571  0.08928571]
 [-0.58928571  0.72678571 -0.13392857]
 [ 0.08928571 -0.13392857  0.02678571]]
[[ 152.6]
 [ 585.6]
 [2488.8]]
[[2.47857143]
 [2.35928571]
 [1.86071429]]


In [9]:
print("the value of a is", C[0] ,
      "the value of b is", C[1] , 
      "the value of c is ",C[2] , 
     )

the value of a is [2.47857143] the value of b is [2.35928571] the value of c is  [1.86071429]


In [1]:
x = [2]
n = 3
n*x

[2, 2, 2]